### ISSUE TITLE
Starter navigator 

### ISSUE THREAD

**Issue by ghost** [zzz945/ReactNativeRelayStarter#2]
Every starter needs a Navigator, and the best option right now seems to be `react-navigation`.

Suggestion: Add  [react-navigation](https://github.com/react-community/react-navigation) to starter

**Comment by zzz945** [comment]
you are right. i will add it

**Comment by zzz945** [comment]
done. try again and please tell me if it has any problem.

**Comment by ghost** [comment]
There seems to be an error on Android:
![start](https://cloud.githubusercontent.com/assets/7504982/23467024/e00419d8-fe6a-11e6-9f4c-1a607bac9343.png)

**Comment by zzz945** [comment]
the  error does not occur for me. I fix some bugs . you can try again.  if that error occur, tell me how to make the error occur.

**Comment by ghost** [comment]
I tried it on Mac/Windows with different android devices, and I still get the same error.
The ios version for iphone works fine
